#!/bin/bash

if [[ "$#" -ne 1 ]]; then
  echo "Usage: $0 <recipient_keyfp>"
  exit 1
fi

[[ -z "$HTTP_PREFIX" ]] && HTTP_PREFIX='http://0:8080'

gpg -vesr "$1" <&0 | \
curl "${HTTP_PREFIX}/cgi-bin/send" \
  -X POST \
  -H "x-sgcc-to: $1" \
  -H 'content-type: application/pgp-encrypted' \
  --data-binary @- \
  -vL
