#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <your_email> [offset]"
  exit 1
fi

your_email="$1"
offset="$2"
[[ -z "$offset" ]] && offset=0

[[ -z "$HTTP_PREFIX" ]] && HTTP_PREFIX='http://0:8080'

message_ids=`curl "${HTTP_PREFIX}/cgi-bin/list.d" -H "x-sgcc-to: $your_email" -vL`

for msgid in $message_ids; do
  curl "${HTTP_PREFIX}/cgi-bin/recv.d" \
    -H "x-sgcc-to: $your_email" \
    -H "x-sgcc-fts: $msgid" \
    -vL | gpg -d
done
